#!/bin/bash

cp buffer_overrun_dynamic.c groups/dynamic_memory_defects/ 
cp buffer_underrun_dynamic.c groups/dynamic_memory_defects/ 
cp cmp_funcadr.c groups/pointer_related_defects/	
cp conflicting_cond.c groups/inappropriate_code/	
cp data_lost.c groups/numerical_defects/	
cp data_overflow.c groups/numerical_defects/	
cp data_underflow.c groups/numerical_defects/	
cp dead_code.c groups/inappropriate_code/	
cp dead_lock.c groups/concurrency_defects/	
cp deletion_of_data_structure_sentinel.c groups/dynamic_memory_defects/	
cp double_free.c groups/resource_management_defects/	
cp double_lock.c groups/concurrency_defects/	
cp double_release.c groups/concurrency_defects/	
cp endless_loop.c groups/misc_defects/	
cp free_nondynamic_allocated_memory.c groups/resource_management_defects/	
cp free_null_pointer.c groups/pointer_related_defects/	
cp func_pointer.c groups/pointer_related_defects/	
cp function_return_value_unchecked.c groups/inappropriate_code/	
cp improper_termination_of_block.c groups/inappropriate_code/
cp insign_code.c groups/misc_defects/	
cp invalid_extern.c groups/misc_defects/	
cp invalid_memory_access.c groups/resource_management_defects/	
cp littlemem_st.c groups/dynamic_memory_defects/	
cp livelock.c groups/concurrency_defects/	
cp lock_never_unlock.c groups/concurrency_defects/	
cp memory_allocation_failure.c groups/resource_management_defects/	
cp memory_leak.c groups/resource_management_defects/	
cp not_return.c groups/misc_defects/	
cp null_pointer.c groups/pointer_related_defects/	
cp overrun_st.c groups/static_memory_defects/	
cp ow_memcpy.c groups/dynamic_memory_defects/	
cp pow_related_errors.c groups/numerical_defects/	
cp ptr_subtraction.c groups/pointer_related_defects/	
cp race_condition.c groups/concurrency_defects/	
cp redundant_cond.c groups/inappropriate_code/	
cp return_local.c groups/resource_management_defects/	
cp sign_conv.c groups/numerical_defects/	
cp sleep_lock.c groups/concurrency_defects/	
cp st_cross_thread_access.c groups/stack_related_defects/	
cp st_overflow.c groups/stack_related_defects/	
cp st_underrun.c groups/stack_related_defects/	
cp underrun_st.c groups/static_memory_defects/	
cp uninit_memory_access.c groups/resource_management_defects/	
cp uninit_pointer.c groups/pointer_related_defects/	
cp uninit_var.c groups/misc_defects/	
cp unlock_without_lock.c groups/concurrency_defects/	
cp unused_var.c groups/inappropriate_code/	
cp wrong_arguments_func_pointer.c groups/pointer_related_defects/	
cp zero_division.c groups/numerical_defects/